spring:
  profiles:
    active: ${MY_ACTIVE_ENV:testing}
---
spring:
  profiles: testing
  data: 
    mongodb:
      uri: 'mongodb+srv://skill_level:${MONGODB_PASSWORD_SKILLLEVEL}@nationwide-ld1bk.azure.mongodb.net/test'

server:
  port: ${SKILLLEVEL_PORT}

---
spring:
  profiles: development
  data: 
    mongodb:
      uri: 'mongodb+srv://skill_level:${MONGODB_PASSWORD_SKILLLEVEL}@nationwide-ld1bk.azure.mongodb.net/test'

server:
  port: ${SKILLLEVEL_PORT}
---
spring:
  profiles: staging
  data: 
    mongodb:
      uri: 'mongodb+srv://skill_level:${MONGODB_PASSWORD_SKILLLEVEL}@nationwide-ld1bk.azure.mongodb.net/test'

server:
  port: ${SKILLLEVEL_PORT}
---
spring:
  profiles: production 
  data: 
    mongodb:
      uri: 'mongodb+srv://skill_level:${MONGODB_PASSWORD_SKILLLEVEL}@nationwide-ld1bk.azure.mongodb.net/test'

server:
  port: ${SKILLLEVEL_PORT}
---

